### ISSUE TITLE
比较神奇的问题，我把代码移植到我的项目当中，在rv 默认展开了，不能折叠

### ISSUE THREAD

**Issue by ousq** [shijiayao-main/ExpandableTextView#1]
但是我用你的demo 也使用 rv  item 一样的情况久不会折叠

**Comment by shijiayao-main** [comment]
不太清楚你在说什么, 但是我对demo进行了一些调整, 没有遇到你说的问题

**Comment by shijiayao-main** [comment]
请确认下具体遇到的问题, 没有问题的话 我将会在明天关闭这个issue

**Comment by shijiayao-main** [comment]
已对demo进行更新, 没有发现对应问题

**Comment by ousq** [comment]
就是这个放在 RecyclerView 列表中直接默认展开了

**Comment by shijiayao-main** [comment]
@ousq 先更新下demo的代码, 看看是否存在你描述的问题, 反馈问题的话需要提供出现问题的截图及对应的代码
